language: java

# This is from https://github.com/travis-ci/travis-ci/issues/9036
# postgresql uses the ramfs, need to increase it so we 
# for TPC-H dataset
before_install: 
        - sudo mount -o remount,size=50% /var/ramfs

jdk:
        - openjdk8

services:
        - postgresql

cache:
  directories:
  - $HOME/.m2

before_script:
        - echo "Installing Emp..."
        - wget https://goo.gl/wmt4KB -O install.sh && bash install.sh > /dev/null 2>&1
        - echo "Completed Emp Install...creating healthlnk testDBs"
        - /bin/bash conf/workload/testDB/create_test_dbs.sh > /dev/null 2>&1
        - echo "Completed HealthLNK testDBs...creating TPC-H DBs"
        - /bin/bash conf/workload/tpch/generate-and-load-data.sh > /dev/null 2>&1

script: mvn --quiet test -B
