name: C/C++ CI

on:
  push:
    branches: [ "emp-operators" ]
  pull_request:
    branches: [ "emp-operators" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ${{github.workspace}}/src/main/cpp
    steps:
    - uses: actions/checkout@v3
    - name: configure cmake
      working-directory: ${{env.working-directory}}
      run: |
          sudo apt-get -y update
          sudo apt-get -y install libboost-dev
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Wno-dev
    - name: Build
      working-directory: ${{env.working-directory}}
      run: cmake --build build --config Release
    - name: Test
      working-directory: ${{env.working-directory}}
      run: ctest --test-dir build
