name: C/C++ CI

on:
  push:
    branches: [ "emp-operators" ]
  pull_request:
    branches: [ "emp-operators" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ${{github.workspace}}/src/main/cpp
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: |
          sudo apt-get -y update
          sudo apt-get -y install libboost-all-dev libgflags-dev postgresql postgresql-client
          wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
          python install.py --deps --tool --ot --zk --sh2pc
          cd ..
          git clone --branch v1.13.0 https://github.com/google/googletest.git
          cd googletest
          cmake .
          make all -j 4
          sudo make install
          cd ..
          git clone --branch 7.7.4 https://github.com/jtv/libpqxx.git
          cd libpqxx
          ./configure  --disable-documentation --enable-shared CXXFLAGS="-std=c++17 -O2"
          make  -j 4
          sudo make install
    - name: configure cmake
      working-directory: ${{env.working-directory}}
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -Wno-dev
    - name: Setup DB
      working-directory: ${{github.workspace}}
      run: | 
          sudo chmod -R 777 /home /home/runner
          sudo adduser --disabled-password --gecos "" vaultdb
          sudo usermod -aG sudo vaultdb && sudo passwd -d vaultdb
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -s vaultdb
          sudo sed -i s/scram-sha-256/trust/g /etc/postgresql/*/main/pg_hba.conf
          sudo sed -i s/peer/trust/g /etc/postgresql/*/main/pg_hba.conf
    - name: Populate DB
      working-directory: ${{github.workspace}}
      run: |
          sudo -u vaultdb bash conf/workload/tpch/generate-and-load-data.sh
          sudo -u postgres createdb tpch_unioned_150
          sudo -u postgres createdb tpch_alice_150
          sudo -u postgres createdb tpch_bob_150
          sudo -u vaultdb psql -U vaultdb -d tpch_unioned_150 -a -f ${{github.workspace}}/src/main/cpp/test/support/tpch_unioned_150.sql
          sudo -u vaultdb psql -U vaultdb -d tpch_alice_150 -a -f ${{github.workspace}}/src/main/cpp/test/support/tpch_alice_150.sql
          sudo -u vaultdb psql -U vaultdb -d tpch_bob_150 -a -f ${{github.workspace}}/src/main/cpp/test/support/tpch_bob_150.sql
    - name: Copy files
      working-directory: ${{env.working-directory}}
      run: |
          cp -a ${{env.working-directory}}/conf ${{env.working-directory}}/build
          cp -a ${{env.working-directory}}/test/support ${{env.working-directory}}/build
          cp ${{env.working-directory}}/runner.py ${{env.working-directory}}/build
          cp ${{env.working-directory}}/run_unit_tests.py ${{env.working-directory}}/build
    - name: Build
      working-directory: ${{env.working-directory}}/build
      run: cmake --build . --config Release -j 4
    - name: Run tests
      working-directory: ${{env.working-directory}}/build
      run: sudo -u vaultdb python run_unit_tests.py 
